### PR TITLE
feat: Prevent registration of new accounts/indexers

### LINKED ISSUE #1015: Prevent creation of new indexers

### PR DESCRIPTION
**Pull request by morgsmccauley**
This PR updates the registry contract to prevent registration of new Accounts and also new Indexer Functions under existing accounts. Most of the changes are making the tests work due to registration now being prevented.

### CODE REVIEW

**Review by darunrs — APPROVED** [review]
Since we're preventing registration of new accounts, should we also disable the add_user function too or just ignore it?

**Comment by gabehamilton** [comment]
Maybe we should check in the previous version of this file as the contract template? In case anyone wants to spin QueryApi up.

**Comment by morgsmccauley** [comment]
> Since we're preventing registration of new accounts, should we also disable the add_user function too or just ignore it?

@darunrs Users are kind of meaningless at this point - I'll ignore for now.

> Maybe we should check in the previous version of this file as the contract template? In case anyone wants to spin QueryApi up.

@gabehamilton good point - I'll deploy this change but not merge.

**Comment by morgsmccauley** [comment]
Deployed to:
✅ `dev-queryapi.dataplatform.near`
✅ `queryapi.dataplatform.near`

**Pull request closed without merging**
