### PR TITLE
Prod Release 17/01/24

### PR DESCRIPTION
**Pull request by morgsmccauley**
- fix: upgrade eslint-config-next from 13.1.6 to 13.5.3
- feat: Make log/state Hasura tables `backend_only` (#462)
- fix: Prune Unnecessary Logs (#465)
- feat: Runner gRPC endpoint (#446)
- feat: Create function to validate types and format from SQL schema
- refactor: Reduce the error states and remove unnecessary Alerts
- refactor: Debounce the schema validation
- chore: Create __tests__ folder for improved folder structure
- feat: Add created/updated at block heights to registry (#458)
- remove side effects from reformatAll function
- refactor: make codeValidation reusable and separate concerns in reformatAll function
- refactor: separate concern con useEffect, and react separately to changes on the indexerDetails object. - Show the schema even if it fails the validations
- fix: remove dead code
- refactor: Replace requestLatestBlockHeight with direct getLatestBlockHeight call
- refactor: Replace requestLatestBlockHeight with direct getLatestBlockHeight call
- refactor: only validate schemas different from the default
- refactor: remove log
- fix: fix issue when generating types, based on response type from astify method
- refactor: decouple ResizableLayourEditor from Editor
- chore: Add description to function
- fix: change reference to variable
- refactor: Make error messages constants
- fix: Solve an issue on the reformatAll function, also added real-time validation when user is changing the code
- fix: Reset errors if code/schemar are ok when reloading
- feat: Create rust GRPC client for Runner (#491)
- feat: Create initial Coordinator V2 service (#444)
- Improve code/schema validation before registering (#495)
- refactor: Remove hard-coded shard count (#502)
- fix: Ensure array is returned to `Promise.all` (#504)
- refactor: Configure `coordinator`/`block-streamer` via environment (#503)

### CODE REVIEW

**Comment by darunrs** [comment]
The two commits that I authored that got added here would require terraform changes in prod. We could either leave them out of this release, or deploy the terraform changes in prod (Added the env variable). I'd probably lean towards leaving it out? Otherwise, the changes looks fine to me. I haven't managed to get to the bottom of the failure in the UI for showing logs though. But if it works for you, then it's definitely not a code issue.

**Review by darunrs — APPROVED** [review]

**Comment by darunrs** [comment]
Did we add start and created block heights to prod contract as well?

**Comment by morgsmccauley** [comment]
> Did we add start and created block heights to prod contract as well?

Yes, it has been deployed to prod.

**Comment by morgsmccauley** [comment]
> The two commits that I authored that got added here would require terraform changes in prod. We could either leave them out of this release, or deploy the terraform changes in prod (Added the env variable). I'd probably lean towards leaving it out? Otherwise, the changes looks fine to me. I haven't managed to get to the bottom of the failure in the UI for showing logs though. But if it works for you, then it's definitely not a code issue.

It's probably easier to apply the terraform changes than revert, and then revert revert those PRs.

What failure in the UI are you referring to?

**Comment by darunrs** [comment]
> > The two commits that I authored that got added here would require terraform changes in prod. We could either leave them out of this release, or deploy the terraform changes in prod (Added the env variable). I'd probably lean towards leaving it out? Otherwise, the changes looks fine to me. I haven't managed to get to the bottom of the failure in the UI for showing logs though. But if it works for you, then it's definitely not a code issue.
> 
> It's probably easier to apply the terraform changes than revert, and then revert revert those PRs.
> 
> What failure in the UI are you referring to?

When I click Show Logs, on any indexer in dev, I get an error. In the console, it shows this error:

image

I'm not entirely sure if this is a local issue or a code issue, quite yet. Chances are it's just me, but I wanted to verify with someone else.

**Comment by morgsmccauley** [comment]
@darunrs yeah that's specific to the dev cert, I've raised an issue with SRE. I'll go ahead and merge this release.

**Pull request merged**
