### PR TITLE
feat: Generate insert and select methods for context object under db

### PR DESCRIPTION
**Pull request by darunrs**
Generates table names from schema. Using the list of table names, it generates an insert and select method for each one. Methods are exposed through 'context.db'. Verified working through local testing against databases in docker image as well as frontend tested using debug mode.

### CODE REVIEW

**Review by roshaans — COMMENTED** [review]
I have not yet gotten a chance to test these changes on an indexer yet. Will report back on this tomorrow.

**Review by morgsmccauley — CHANGES_REQUESTED** [review]
Good job on this. I've left a few comments, happy to help you work through any of them :)

**Review by morgsmccauley — DISMISSED** [review]
Good job on this. I've left a few comments, happy to help you work through any of them :)

**Review by morgsmccauley — COMMENTED** [review]
Making some good progress here, left a few more comments, mostly around code placement :)

**Pull request merged**
